name: 'Setup dependencies'
description: 'Install or restore dependencies'
inputs:
  nodeLinker:
    description: 'nodeLinker for yarn v3'
    required: false
    default: 'node-modules'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
      # env:
      #   PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - uses: actions/cache@v3
      id: yarn_cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn config set nodeLinker ${{ inputs.nodeLinker }}
      shell: bash

    - if: ${{ steps.yarn_cache.outputs.cache-hit != 'true' }}
      run: yarn install
      shell: bash
