name: 'Setup dependencies'
description: 'Install or restore dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
      # env:
      #   PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - uses: actions/cache@v3
      id: yarn_cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - if: ${{ steps.yarn_cache.outputs.cache-hit != 'true' }}
      run: yarn install
      shell: bash
