name: 'Setup'
description: 'Set up and install dependencies'
runs:
  using: 'composite'
  steps:
    - name: Display version of Node.js, npm, Yarn
      run: |
        node -v
        npm -v
        yarn -v
      shell: bash
    - name: Install Dependencies
      run: yarn
      shell: bash
