name: Bug Report
description: Report a bug in the project
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A detail of the bug you see.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What behavior should happen?
      description: A behavior you expect.
      placeholder: Tell us what you expect!
    validations:
      required: true
  - type: textarea
    id: reproduction-procedure
    attributes:
      label: How can we reproduce this?
      description: How to reproduce this bug.
      placeholder: Tell us reproduction procedure!
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: You may select more than one option.
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: textarea
    id: browsers-version
    attributes:
      label: What version of browser?
      description: If you selected "Other" for the question above, please also tell us the name of the browser you are using.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com, sns's username etc...
