name: Feature Request
description: Request for the feature you would like.
title: '[Feature] '
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-feature
    attributes:
      label: What is the feature you would like?
      description: A detail of the feature you would like.
      placeholder: Tell us what you would like!
    validations:
      required: true
  - type: textarea
    id: why-needed
    attributes:
      label: What is this feature needed?
      description: Please tell us why this feature is needed for the project.
      placeholder: Tell us why this feature is needed!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com, sns's username etc...
