name: 'CI'

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: ./.github/actions/setup
      - name: Build
        run: yarn build
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
  type-check:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Type Check
        run: yarn type-check
  test:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
