name: 'Run CI'

on:
  - pull_request

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: yarn lint

  CodeQL-Analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: typescript, javascript
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: yarn type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: yarn test

  storybook-deploy:
    name: Storybook Deploy
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: cd packages/takudev-web && yarn build:storybook
      - run: |
          DEST_DIR=${{ github.event.pull_request.number }}
          [ -z $DEST_DIR ] && DEST_DIR=develop
          echo "DEST_DIR=${DEST_DIR}" >> $GITHUB_ENV
      - run: |
          aws s3 cp --recursive \
            ./packages/takudev-web/dist-storybook \
            s3://takudev-storybook/storybook/${DEST_DIR}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
      - if: github.event.action == 'opened'
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'storybook preview created!!\n' +
                'https://takudev-storybook.s3-ap-northeast-1.amazonaws.com/storybook/${{ github.event.pull_request.number }}/index.html'
            })

  storybook-clean:
    name: Storybook Clean
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    if: github.event.action == 'closed'
    steps:
      - run: |
          DEST_DIR=${{ github.event.pull_request.number }}
          aws s3 rm --recursive \
            s3://takudev-storybook/storybook/${DEST_DIR}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
