name: 'Measure Core Web Vitals'

on:
  - push

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      # - uses: browser-actions/setup-chrome@latest
      # - run: chrome --version
      - run: yarn build
        env:
          HOST: ${{ secrets.HOST }}
          STRAPI_JWT_TOKEN: ${{ secrets.STRAPI_JWT_TOKEN }}
      - run: |
          npm install -g @lhci/cli@0.10.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
