name: 'Run CI'

on:
  - push

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - run: yarn build
      - run: |
          npm install -g @lhci/cli@0.10.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
