name: 'Run CI'

on:
  - push

jobs:
  reg-suit:
    name: Reg Suit
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-dependencies
      - run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - run: npm install -g puppeteer
      - run: cd packages/takudev-web && yarn storycap
      - run: cd packages/takudev-web && yarn reg-suit run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REG_SUIT_GITHUB_APP_CLIENT_ID: ${{ secrets.REG_SUIT_GITHUB_APP_CLIENT_ID}}
