name: 'Run VRT'

on:
  - push

jobs:
  reg-suit:
    name: Reg Suit
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Storycap
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 5
          command: yarn storycap

      - name: Run Reg Suit
        run: yarn reg-suit run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REG_SUIT_GITHUB_APP_CLIENT_ID: ${{ secrets.REG_SUIT_GITHUB_APP_CLIENT_ID}}
