name: 'reg-suit'
on: [push]

jobs:
  reg-suit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: ./.github/actions/setup
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: Build Storybook
        run: cd packages/takudev-web && yarn build:storybook
      - name: Capture Screenshots
        run: cd packages/takudev-web && yarn storycap
      - name: Run Reg-suit
        run: cd packages/takudev-web && yarn reg-suit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REG_SUIT_GITHUB_APP_CLIENT_ID: ${{ secrets.REG_SUIT_GITHUB_APP_CLIENT_ID}}
