name: 'CI'

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - 'main'
      - 'develop'
      - 'staging'
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - '**patch**'

jobs:
  semantic-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
