name: 'Run CI'

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  semantic-pr-title:
    name: 'Semantic PR Title'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
